### ISSUE TITLE
Andy feedback

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tt_asw_1v8#1]
1) Increase from minimum width on all metal layers (I'd shoot for 2x minimum,) Sheet resistance variability will then dominate instead of line width error.
2) Double or triple all vias, contacts and Licon in teh signal path. (Not necessary in the control path) Especially contacts, Licon, mcon where possible.
(These devices are high resistance with high variability and so increasing the number of them reduces their absolute fractinon of total impedance and therefore total variabilty contribution.
3) If the signals being routed are sensitive consider avoiding ever having parallel runs of disconnected signals if possible other than on the transistor legs.
This is normally achieved by having inputs on one side of a device and outputs go to the other and then reversing that direction for next device to minimize crossings.
4) Consider having a dummy devices on the outside edges of a set of transistors to minimize modelling error if you care deeply about device performance to the models.
5) If you need multiple mux paths to have identical performance you should consider common centroid and transistor matching current flow directions.
(Matched Fets should have the current flow same direction (North to south, east to west etc). THis minimizes the effect of channel doping variation as a result of implant angles.
6) If the layout your control path devices seem large (which is only required if you want to switch to connect or disconnect analog signals quickly)
7) There is no ground isolation device in your mux so there is a capacitance directly between input and output of the transmission gate pair. A better structure has Mux one, switched isolation to ground followed by mux 2. (Bigger layout but) This makes no difference for 4-8 bit analog but at 10 bits or beyond this will matter a lot. Cross talk between isolated analog signals is a source of systematic analog noise.

**Comment by urish** [comment]
Regarding point 6: 

> If the layout your control path devices seem large (which is only required if you want to switch to connect or disconnect analog signals quickly)

We don't need to switch analog signals quickly (only during design selection)

**Comment by smunaut** [comment]
1+2: Agree
3: Not 100% sure what he mean, but in anycase doesn't sound like a concern for us
4: I don't think it's a big concern here
5: Not doable for TT, each mux has to be it's own separate entity, there is no way we can do common centroid layout for all the paths. Also the rest of the path wouldn't be matched either anyway.
6: Definitely looks large to me too, especially compared to like 2 * `inv_4` cells which is what we're aiming for basically.
7: Not doable in TT, but anyway we're not concerned about capacitive coupling really, the other tiles are not even powered so they can't cross talk ... we're more concerned about leakage and parasitic capacitance.
