### ISSUE TITLE
check the extract script

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tt_asw_1v8#3]
why generates 2 versions
what about the -d

![image](https://github.com/TinyTapeout/tt_asw_1v8/assets/634220/73bf9e72-b425-44c3-91ae-4df38a6b3444)

https://discord.com/channels/1009193568256135208/1162428058817540116/1226529300665204746

**Comment by smunaut** [comment]
Checked with Tim, `-d` is deprecated, so got rid of it and now call `ext2spice` only once to generate `.sim.spice` file.
